name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security checks weekly
    - cron: '0 2 * * 1'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit
      run: npm audit --audit-level=moderate
      
    - name: Check for known vulnerabilities
      run: |
        # Create audit report
        npm audit --json > audit-report.json || true
        
        # Check if there are high or critical vulnerabilities
        HIGH_VULNS=$(cat audit-report.json | grep -o '"severity":"high"' | wc -l)
        CRITICAL_VULNS=$(cat audit-report.json | grep -o '"severity":"critical"' | wc -l)
        
        echo "High vulnerabilities found: $HIGH_VULNS"
        echo "Critical vulnerabilities found: $CRITICAL_VULNS"
        
        if [ "$CRITICAL_VULNS" -gt 0 ]; then
          echo "❌ Critical vulnerabilities found! Please address immediately."
          exit 1
        elif [ "$HIGH_VULNS" -gt 0 ]; then
          echo "⚠️ High vulnerabilities found. Consider addressing soon."
          exit 1
        else
          echo "✅ No critical or high vulnerabilities found."
        fi

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Check for outdated dependencies
      run: |
        npm outdated || true
        echo "Dependency check completed"